version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env-prod
    volumes:
      - /postgres:/data_db
    environment:
      POSTGRES_PASSWORD: password


  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: app
    ports:
      - 5500:5500
    depends_on:
      - db