version: "3.7"
services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env-prod
    volumes:
      - /postgres:/data_db
    environment:
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: DockerfileAPP
    env_file:
      - .env-prod
    container_name: app
    ports:
      - 5500:5500
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: DockerfileBOT
    env_file:
      - .env-prod
    container_name: bot

