version: "3.7"
services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env-prod
    volumes:
      - /postgres:/data_db
    environment:
      POSTGRES_PASSWORD: password


